services:
  - type: web
    name: ytmp3-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && playwright install && playwright install-deps
    startCommand: gunicorn app:app
